### ISSUE TITLE
KubeFlow on Sykube

### ISSUE THREAD

**Issue by kimchitsigai** [sylabs/sykube#7]
Hi,

I've installed Singularity 3.5.1 and Sykube on Ubuntu 18.04. Everything runs fine.

Now I'd like to install KubeFlow 0.7 as described in https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/.
The KubeFlow installation program, kfctl, needs to connect to the K8s API server. In a "normal" cluster, kfctl looks for the connection parameters (url, certificate, etc.) in /etc/kubernetes/admin.conf file.

What information should I provide in admin.conf to enable kfctl to connect to the Sykube cluster ?

Thanks a lot.

**Comment by kimchitsigai** [comment]
My environment is:

```
root@jinmsi:~/kubeflow# singularity version
3.5.1

root@jinmsi:~/kubeflow# go version
go version go1.13.5 linux/amd64

root@jinmsi:~/kubeflow# cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"

```

**Comment by cclerget** [comment]
Hi @kimchitsigai and sorry for the late response, I think you will need to grab `/etc/kubernets/admin.conf` from master instance like this :

```
mkdir ~/.kube
sykube exec master cat /etc/kubernetes/admin.conf >> ~/.kube/config
```
